// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PARCIAL1.Data;

#nullable disable

namespace PARCIAL1.Migrations
{
    [DbContext(typeof(EmpleadosContext))]
    [Migration("20230430221718_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("PARCIAL1.Models.Empleados", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ambiguedad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("edad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("sueldo")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("PARCIAL1.Models.Puestos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Empleadosid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("puesto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Empleadosid");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("PARCIAL1.Models.Puestos", b =>
                {
                    b.HasOne("PARCIAL1.Models.Empleados", "Empleados")
                        .WithMany("Puestos")
                        .HasForeignKey("Empleadosid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("PARCIAL1.Models.Empleados", b =>
                {
                    b.Navigation("Puestos");
                });
#pragma warning restore 612, 618
        }
    }
}
